### ISSUE TITLE
Moby packages in packages-microsoft-com-prod conflict with Docker CE on RHEL 9 (moby-cli obsoletes docker-ce)

### ISSUE THREAD

**Issue by jasonheffnerpsu** [microsoft/linux-package-repositories#290]
### Summary

A recent update to the `packages-microsoft-com-prod` repository introduced
Moby packages (e.g., `moby-cli`, `moby-engine`) that now declare:

- Conflicts: docker-ce
- Obsoletes: docker-ce

This is new behavior. As a result, systems that use Docker CE on RHEL 9 /
Rocky 9 / Alma 9 can no longer perform `dnf upgrade` or install
docker-ce-related packages if the Microsoft repo is enabled — even though
Moby is *not* installed.

---

### What Happens

With the Microsoft repo enabled:
sudo dnf upgrade

fails with errors such as:

Problem 1: package docker-ce-rootless-extras-29.1.2-1.el9.x86_64 from @System requires docker-ce, but none of the providers can be installed
  - package moby-cli-29.1.2-1.el9.x86_64 from packages-microsoft-com-prod conflicts with docker-ce provided by docker-ce-3:29.1.2-1.el9.x86_64 from @System
  - package moby-cli-29.1.2-1.el9.x86_64 from packages-microsoft-com-prod obsoletes docker-ce provided by docker-ce-3:29.1.2-1.el9.x86_64 from @System

Simply having the repo enabled causes this conflict.

### Expected Behavior

Moby packages should be installable as an alternative runtime, but should
not forcibly replace or conflict with Docker CE unless the user explicitly
chooses to install Moby.

---

### Impact

Many systems rely on this repo for Azure CLI or .NET. After the recent
change, these systems must now disable the entire Microsoft repo or add
manual excludes just to use Docker CE.

---

### Request

Could the `Conflicts:` and `Obsoletes:` rules for `docker-ce` be reviewed
or relaxed so both repositories can coexist again?

**Comment by cpuguy83** [comment]
The bad packages have been removed and should resolve the particular issue.

We also have changes pending to remove that conflicts/obsoletes metadata from the new builds.

**Comment by Klaas-** [comment]
The same thing happened a couple of years(?) back, I had to complain via support ticket. I am guessing no one thought to built a QA test for this, maybe do that now so it doesn't come back next time you change build pipelines? :)

**Comment by msancarneiro** [comment]
> The bad packages have been removed and should resolve the particular issue.
> 
> We also have changes pending to remove that conflicts/obsoletes metadata from the new builds.

Have the packages for RHEL 8 also been removed? We are still seeing Obsoletes/Conflicts in RHEL 8.10 with moby-cli-29.1.2-1.el8.x86_64.
