### ISSUE TITLE
unixodbc packages conflict with upstream packages on Ubuntu 22.04 and Debian 11

### ISSUE THREAD

**Issue by dlech** [microsoft/linux-package-repositories#39]
**Describe the issue**
I'm getting errors from apt about `unixodbc` packages.

```
$ sudo apt install -f
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libodbc1 odbcinst odbcinst1debian2
Suggested packages:
  msodbcsql17 unixodbc-bin
The following NEW packages will be installed:
  libodbc1 odbcinst odbcinst1debian2
0 upgraded, 3 newly installed, 0 to remove and 9 not upgraded.
2 not fully installed or removed.
Need to get 0 B/607 kB of archives.
After this operation, 945 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
(Reading database ... 754326 files and directories currently installed.)
Preparing to unpack .../odbcinst_2.3.11_amd64.deb ...
Unpacking odbcinst (2.3.11) ...
dpkg: error processing archive /var/cache/apt/archives/odbcinst_2.3.11_amd64.deb
 (--unpack):
 trying to overwrite '/etc/odbc.ini', which is also in package unixodbc-common 2
.3.9-5
Preparing to unpack .../odbcinst1debian2_2.3.11_amd64.deb ...
Unpacking odbcinst1debian2:amd64 (2.3.11) ...
dpkg: error processing archive /var/cache/apt/archives/odbcinst1debian2_2.3.11_a
md64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libodbcinst.so.2.0.0', which is 
also in package libodbcinst2:amd64 2.3.9-5
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../libodbc1_2.3.11_amd64.deb ...
Unpacking libodbc1:amd64 (2.3.11) ...
dpkg: error processing archive /var/cache/apt/archives/libodbc1_2.3.11_amd64.deb
 (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libodbc.so.2.0.0', which is also
 in package libodbc2:amd64 2.3.9-5
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/odbcinst_2.3.11_amd64.deb
 /var/cache/apt/archives/odbcinst1debian2_2.3.11_amd64.deb
 /var/cache/apt/archives/libodbc1_2.3.11_amd64.deb
```

**When did the issue occur?**
14 Febuary, 2023

**If applicable, what package did you attempt to install, and from which repo?**

Just doing automatic apt update. `libodbc2` is used by many packages (unrelated to Microsoft). I have `http://packages.microsoft.com/` in my apt sources for VS Code.

**Steps to Reproduce**

- Install an Ubuntu app that uses `libodbc2`, for example `blender`.
- Set up  `http://packages.microsoft.com/`
- Try to do an apt upgrade.

**Actual Result**

Apt fails because of conflicts. The Microsoft version of the package is shipping the v2 library in a `libodbc1` package instead of a `libodbc2` package. Apt tries to install both at the same time and it can't because both packages try to install the same file.

**Expected Result**

Microsoft should not be shipping updates to upstream packages in a general package archive like this. Or at minimum, it should be opt-in rather than opt out.

**Screenshots**

**Additional context**

**Comment by rajpawar02** [comment]
I'm having the same problem running CI on the GitHub action runner ( Ubuntu 22.04.1). The details of the error are as follows:

```
Preparing to unpack .../0-libodbc1_2.3.11_amd64.deb ...
Unpacking libodbc1:amd64 (2.3.11) ...
dpkg: error processing archive /tmp/apt-dpkg-install-nDLQ5L/0-libodbc1_2.3.11_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libodbc.so.2.0.0', which is also in package libodbc2:amd64 2.3.9-5
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package odbcinst1debian2:amd64.
Preparing to unpack .../1-odbcinst1debian2_2.3.11_amd64.deb ...
Unpacking odbcinst1debian2:amd64 (2.3.11) ...
dpkg: error processing archive /tmp/apt-dpkg-install-nDLQ5L/1-odbcinst1debian2_2.3.11_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libodbcinst.so.2.0.0', which is also in package libodbcinst2:amd64 2.3.9-5
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../2-odbcinst_2.3.11_amd64.deb ...
Unpacking odbcinst (2.3.11) over (2.3.9-5) ...
dpkg: error processing archive /tmp/apt-dpkg-install-nDLQ5L/2-odbcinst_2.3.11_amd64.deb (--unpack):
 trying to overwrite '/etc/odbc.ini', which is also in package unixodbc-common 2.3.9-5
Selecting previously unselected package postgresql-client.
Preparing to unpack .../3-postgresql-client_14+238_all.deb ...
Unpacking postgresql-client (14+238) ...
Preparing to unpack .../4-unixodbc_2.3.11_amd64.deb ...
Unpacking unixodbc (2.3.11) over (2.3.9-5) ...
Preparing to unpack .../5-unixodbc-dev_2.3.11_amd64.deb ...
Unpacking unixodbc-dev (2.3.11) over (2.3.9-5) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-nDLQ5L/0-libodbc1_2.3.11_amd64.deb
 /tmp/apt-dpkg-install-nDLQ5L/1-odbcinst1debian2_2.3.11_amd64.deb
 /tmp/apt-dpkg-install-nDLQ5L/2-odbcinst_2.3.11_amd64.deb
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
Error: Process completed with exit code [100](https://github.com/patterninc/shipmentczar/actions/runs/4179207866/jobs/7242081737#step:6:101).

```
 
Anyone know of a solution?

**Comment by Mause** [comment]
Looks like this has been raised in https://bugs.launchpad.net/ubuntu/+source/unixodbc/+bug/2006998 and https://bugs.launchpad.net/ubuntu/+source/unixodbc/+bug/2007288 (the second one includes a hack fix)

**Comment by fdellwing** [comment]
Having the same problem here today with with `libodbc1` package.

**Comment by thordevsecops** [comment]
Hi everyone, this problem persist in Ubuntu alternatives Distro (Pop OS, Zorin and Linux Mint).

This problem broken command apt dist-upgrade and Erlang Kerl Compile (Unixodbc is necessary to Erlang Kerl native or ASDF).

This temporary solution for me to use Ubuntu normally is:

sudo dpkg --remove unixodbc

sudo dpkg --remove unixodbc-dev

I'm commenting on this issue to keep track of possible solutions.

**Comment by fdellwing** [comment]
The only feasible long term solution is for MS to fix their repo.

**Comment by manitgupta** [comment]
Facing the same issue with out of the blue in our GIthub action runner today:

```
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 236141 files and directories currently installed.)
Preparing to unpack .../0-libodbc1_2.3.11_amd64.deb ...
Unpacking libodbc1:amd64 (2.3.11) ...
dpkg: error processing archive /tmp/apt-dpkg-install-6gccu1/0-libodbc1_2.3.11_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libodbc.so.2.0.0', which is also in package libodbc2:amd64 2.3.9-5
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package odbcinst1debian2:amd64.
Preparing to unpack .../1-odbcinst1debian2_2.3.11_amd64.deb ...
Unpacking odbcinst1debian2:amd64 (2.3.11) ...
dpkg: error processing archive /tmp/apt-dpkg-install-6gccu1/1-odbcinst1debian2_2.3.11_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libodbcinst.so.2.0.0', which is also in package libodbcinst2:amd64 2.3.9-5
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../2-odbcinst_2.3.11_amd64.deb ...
Unpacking odbcinst (2.3.11) over (2.3.9-5) ...
dpkg: error processing archive /tmp/apt-dpkg-install-6gccu1/2-odbcinst_2.3.11_amd64.deb (--unpack):
 trying to overwrite '/etc/odbc.ini', which is also in package unixodbc-common 2.3.9-5
Preparing to unpack .../3-unixodbc_2.3.11_amd64.deb ...
Unpacking unixodbc (2.3.11) over (2.3.9-5) ...
```

**Comment by signedav** [comment]
@rajpawar02 Fixed my CIs by installing the odbc stuff before adding the MS repositories according to this input https://bugs.launchpad.net/ubuntu/+source/unixodbc/+bug/2007288/comments/3

See https://github.com/opengisch/QgisModelBakerLibrary/pull/54/commits/a6dfc8eea64867290b335c7375e436b00be224fd

**Comment by manitgupta** [comment]
I tried the suggested workaround in [bug](https://bugs.launchpad.net/ubuntu/+source/unixodbc/+bug/2007288/comments/3) but it did not work for me -

Commit - https://github.com/manitgupta/harbourbridge/commit/e30062a9a74bc703bb58816f5e2457a80d7547a4
Failed run - https://github.com/manitgupta/harbourbridge/actions/runs/4183240613/jobs/7247347511

**Comment by dlech** [comment]
For desktop users that don't want/need the Microsoft version of unixodbc, you can add the following to `/etc/apt/preferences.d/microsoft`:

```
Package: unixodbc
Pin: origin "packages.microsoft.com"
Pin-Priority: 100
Package: unixodbc-dev
Pin: origin "packages.microsoft.com"
Pin-Priority: 100
```

**Comment by fdellwing** [comment]
Even though no one from MS wrote something here, the package seems to habe been removed from the repository again and therefore this issue should no longer exist.

**Comment by fjudith** [comment]
> Even though no one from MS wrote something here, the package seems to habe been removed from the repository again and therefore this issue should no longer exist.

I confirm, the issue seems solved.

**Comment by thordevsecops** [comment]
I execute dist-upgrade in my Ubuntu 22.04 is not having issue in Microsoft repository.

Installation proceed normaly in Unixodbc and Unixodbc-dev.

**Comment by manitgupta** [comment]
Yes, solved now.

**Comment by falkben** [comment]
running this again this morning, I'm still seeing `2.3.11` being installed with a reference to the wrong header

```docker
FROM --platform=linux/amd64 python:3.8-bullseye

RUN \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install --yes \
    msodbcsql17 \
    unixodbc-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/* 

RUN \
    pip install --no-binary :all: pyodbc
```

pinning `unixodbc-dev=2.3.7 unixodbc=2.3.7 odbcinst1debian2=2.3.7 odbcinst=2.3.7` still works

**Comment by fdellwing** [comment]
@falkben This was so far about the Ubuntu 22 repo. It seems that the Debian 11 repo is also and still affected (while Ubuntu is fixed).

**Comment by ethrya** [comment]
I understand that I am still having this issue on Ubuntu 20.04. And it looks like the packages have not been removed from the packages files

I can also still see the additional packages (e.g. libodbc) here: https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/)

**Comment by alanplarium** [comment]
It is still failing for me. Anyone else still could not resolve the issue?

**Comment by David-Engel** [comment]
This should be addressed now. The unixodbc 2.3.11 packages were removed for Ubuntu 22.04 and higher. Use the unixodbc packages provided by Ubuntu. For Debian 10, 11, and Ubuntu 20.04, 18.04, an updated package, 2.3.11-1, was published with a fix for the header issue.

**Comment by alanplarium** [comment]
@David-Engel It is still failing for me. I am building a docker image and fails in one of these steps:

`RUN apt-get install -y gnupg2`

`RUN sudo su \
&& curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
&& curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list`

I get these errors:
`dpkg: error processing archive /var/cache/apt/archives/libodbc1_2.3.11-1_amd64.deb (--unpack):`
`dpkg: error processing archive /var/cache/apt/archives/odbcinst1debian2_2.3.11-1_amd64.deb (--unpack):`

Anything you think I should change?

**Comment by sheikx1221** [comment]
removing these packages is a pain you don't want to feel
here is the therapy

`sudo dpkg --remove unixodbc-dev unixodbc`

then you need to edit postrm script of msodbcsql17 using root
`sudo vim /var/lib/dpkg/info/msodbcsql17.postrm`

comment the two lines in postrm that start with odbcinst and db_purge in the remove section and save

`sudo apt-get remove msodbcsql17`
`sudo apt remove unixodbc unixodbc-dev odbcinst odbcinst1debian2 libodbc1 msodbcsql17 mssql-tools`

Then follow this [tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-mysql-on-ubuntu-22-04) for 22.04 ubuntu desktop

**Comment by geekdenz** [comment]
I worked around and solved it by 

`sudo vi /etc/apt/sources.list.d/msprod.list`

Comment out the line(s):

```bash
#deb [arch=amd64,armhf,arm64] https://packages.microsoft.com/ubuntu/20.04/prod focal main
```

Run

```bash
sudo apt update && sudo apt --fix-broken install
```

Then reinstall MS products by doing the reverse if desired.

**Comment by Yaroslav285** [comment]
Hello, I tried to use Ubuntu's MS repo in Debian 11 and it works.

https://packages.microsoft.com/config/ubuntu/22.04/prod.list

For Debian's repo, it generates an error 


```hared/StringFunctions.lo -Wl,-z,now -lstdc++ -lodbc -lodbcinst
#4 46.78 libtool: link: warning: library `/usr/lib/x86_64-linux-gnu/libodbc.la' was moved.
#4 46.79 grep: /usr/lib/x86_64-linux-gnu/libltdl.la: No such file or directory
#4 46.79 /bin/sed: can't read /usr/lib/x86_64-linux-gnu/libltdl.la: No such file or directory
#4 46.79 libtool: link: `/usr/lib/x86_64-linux-gnu/libltdl.la' is not a valid libtool archive
#4 46.79 make: *** [Makefile:249: sqlsrv.la] Error 1
#4 46.79 ERROR: `make' failed```

after running the command

`pecl install sqlsrv`

**Comment by lwohlhart** [comment]
We are running php with mssql driver in our production server cluster.  ( currently all machines are on ubuntu 18.04, in the process of upgrading to 22.04 )
We are also currently solving the issue by pinning the repository such that we don't recieve the problematic `unixodbc` and `unixodbc-dev` packages hosted in the microsoft repo. Similar to https://github.com/microsoft/linux-package-repositories/issues/39#issuecomment-1431791428
pecl installation of the drivers would break as other described before me.

@David-Engel could you please comment on why it's necessary for microsoft to host these packages in general? 
Are we going to run into other sorts of incompatiblities if we don't install your packge. imho this would be a bit odd for a package like unixodb

**Comment by moerkey** [comment]
> For desktop users that don't want/need the Microsoft version of unixodbc, you can add the following to `/etc/apt/preferences.d/microsoft`:
> 
> ```
> Package: unixodbc
> Pin: origin "packages.microsoft.com"
> Pin-Priority: 100
> Package: unixodbc-dev
> Pin: origin "packages.microsoft.com"
> Pin-Priority: 100
> ```

For me, that wasn´t sufficient under Ubuntu 18.04. I think it is important to add a new line between the two sections like this.

```
Package: unixodbc
Pin: origin "packages.microsoft.com"
Pin-Priority: 100

Package: unixodbc-dev
Pin: origin "packages.microsoft.com"
Pin-Priority: 100
```

Also I had to add more packages. So my total pinning looks like this.
```
# https://github.com/microsoft/linux-package-repositories/issues/39#issuecomment-1431791428

Package: unixodbc
Pin: origin "packages.microsoft.com"
Pin-Priority: 100

Package: unixodbc-dev
Pin: origin "packages.microsoft.com"
Pin-Priority: 100

Package: libodbc1:amd64
Pin: origin "packages.microsoft.com"
Pin-Priority: 100

Package: odbcinst
Pin: origin "packages.microsoft.com"
Pin-Priority: 100

Package: odbcinst1debian2:amd64
Pin: origin "packages.microsoft.com"
Pin-Priority: 100
```

Btw I didn´t understand the intention but nice way to solve it via lowering the pin priority.

**Comment by lucasmichel** [comment]
In case anyone has the same problem I solved it as follows:

change url  https://packages.microsoft.com/config/debian/11/prod.list 
from  https://packages.microsoft.com/config/ubuntu/22.10/prod.list

change msodbcsql17 from msodbcsql18

going like this:

```
RUN cat /etc/os-release \
  && apt-get update \
  && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
  && curl https://packages.microsoft.com/config/ubuntu/22.10/prod.list \
      > /etc/apt/sources.list.d/mssql-release.list \
  && apt-get install -y --no-install-recommends apt-transport-https \
  && apt-get update \
  && ACCEPT_EULA=Y apt-get -y --no-install-recommends install unixodbc-dev msodbcsql18  
```

**Comment by Yaroslav285** [comment]
Hello @lucasmichel, it works for me too. That's what I mentioned in my comment

> Hello, I tried to use Ubuntu's MS repo in Debian 11 and it works.
> 
> https://packages.microsoft.com/config/ubuntu/22.04/prod.list
> 
> For Debian's repo, it generates an error
> 
> ```
> #4 46.78 libtool: link: warning: library `/usr/lib/x86_64-linux-gnu/libodbc.la' was moved.
> #4 46.79 grep: /usr/lib/x86_64-linux-gnu/libltdl.la: No such file or directory
> #4 46.79 /bin/sed: can't read /usr/lib/x86_64-linux-gnu/libltdl.la: No such file or directory
> #4 46.79 libtool: link: `/usr/lib/x86_64-linux-gnu/libltdl.la' is not a valid libtool archive
> #4 46.79 make: *** [Makefile:249: sqlsrv.la] Error 1
> #4 46.79 ERROR: `make' failed```
> 
> after running the command
> 
> `pecl install sqlsrv`
> ```


I hope Microsoft engineers are going to perform some actions to resolve the issue as well for Debian 11.

**Comment by David-Engel** [comment]
> could you please comment on why it's necessary for microsoft to host these packages in general?
> Are we going to run into other sorts of incompatiblities if we don't install this version of the package?

@lwohlhart 

We provide builds of unixodbc because we submit bug fixes to unixodbc that were found in the course of troubleshooting customer issues. Linux distributions tend to lag quite a bit behind in updating to newer versions of unixodbc (some more than others). 2.3.7 should be considered a minimum version to run, bug wise, with 2.3.9 being the next best step, in our experience. You should not run into incompatibilities if you don't install the latest version.

Regards,
David

**Comment by tclrl** [comment]
hi,
same problem here. i use debian 11. i've installed theses packages : 
php8.2 : https://packages.sury.org/ 8.2.3-1+0~20230214.16+debian11~1.gbpd66462
libodbc1 : http://deb.debian.org/debian 2.3.6-0.1+b1
unixodbc : http://deb.debian.org/debian 2.3.6-0.1+b1
unixodbc-dev  : http://deb.debian.org/debian 2.3.6-0.1+b1
msodbcsql18 : https://packages.microsoft.com/ubuntu/22.10/prod 18.2.1.1-1


it's work but the package went from ubuntu

**Comment by sdherr** [comment]
Is there still a problem here or can I close this issue? I've tested things out in Debian 11 and Ubuntu 18.04 and it seems to work currently. If something is still broken we need a more clear reproducer.

From an arbitrary machine with docker (or similar) installed: `docker run -it debain:11` (or `ubuntu:18.04`):
```
apt-get update
apt-get install wget blender
wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb
# or, on Ubuntu:
# wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
apt-get install ./packages-microsoft-prod.deb
apt-get update
apt-get upgrade
# -> works
```

**Comment by dlech** [comment]
It's been a few weeks since any chatter, so I'll go ahead and close it and see if anyone objects.

**Comment by fcorrigabb** [comment]
The problem is still there.

**Comment by pborquez** [comment]
Until today, the problem is still here but this is the way I solved the issue using a Debian image:

```Dockerfile
FROM php:8.2.1-apache-bullseye as production

RUN set -eux; \
  apt-get update; \
  apt-get install -y --no-install-recommends \
    gnupg \
    wget \
    curl \
  ; \
  curl -SL --progress-bar https://packages.microsoft.com/keys/microsoft.asc | apt-key add -; \
  curl -SL --progress-bar https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list; \
  apt-get update; \
  ACCEPT_EULA=Y apt-get install -y msodbcsql18; \
  apt-get install -y unixodbc-dev; \
  sed -i -E 's/(CipherString\s*=\s*DEFAULT@SECLEVEL=)2/\11/' /etc/ssl/openssl.cnf; \
  rm -rf /var/lib/apt/lists/*;

RUN set -eux; \
  pecl install \
    sqlsrv \
    pdo_sqlsrv \
  ; \
  docker-php-ext-enable \
    sqlsrv \
    pdo_sqlsrv \
  ; \
  echo "extension= pdo_sqlsrv.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`; \
  echo "extension= sqlsrv.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`;
```

**Comment by rb12345** [comment]
It might be worth noting that this breaks upgrades from bullseye to bookworm if anything else depends on the library.

**Comment by ameryu716** [comment]
＞ @pborquez 
`curl -SL --progress-bar https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list; \`
Acturally thanks!!
I was freed from the bondage of two hours.

**Comment by killerkalamari** [comment]
This got me past the problem on a Debian 11 to 12 upgrade: `sudo apt remove python3-gdal libgdal32 libgdal28 libodbc1`

**Comment by mangelozzi** [comment]
Why is this issue closed? It is still broken with Ubuntu 22.04.

**Comment by fcorrigabb** [comment]
It's in the initial report.

**Comment by sdherr** [comment]
Okay, I can now reproduce the issue. Building this Dockerfile for example fails:
```
FROM debian:11

RUN apt update
RUN apt install -y gpg curl php-dev
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt update

RUN ACCEPT_EULA=Y apt install -y msodbcsql18 mssql-tools18
RUN apt install -y unixodbc-dev
RUN pecl install sqlsrv
```

This appears to be a duplicate of [this issue](https://github.com/microsoft/msphpsql/issues/1436), where they note not only the "use the Ubuntu repo" workaround but also a "use an older version of unixodbc" workaround:
```
&& ACCEPT_EULA=Y apt-get install -y msodbcsql17 odbcinst=2.3.7 odbcinst1debian2=2.3.7 unixodbc-dev=2.3.7 unixodbc=2.3.7 \
```

The root cause appears to be (and here I'm only reading the comments in that issue) that these packages were built from a broken version of upstream `unixodbc=2.3.11`, which was later fixed in `unixodbc=2.3.11-2`. Fixing the packages in the Microsoft repo would involve rebuilding them on the fixed -2 version.

I recommend everyone move this discussion to that issue, since it's actually filed against the team that can help here. I'll also ping them internally with the reproducer and explanation.

**Comment by SirArthur7** [comment]
I found the following code snippet from Microsoft page [Install the Microsoft ODBC driver for SQL Server (Linux)](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16&tabs=ubuntu18-install%2Calpine17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline)](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16&tabs=ubuntu18-install%2Calpine17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline) work perfectly fine-

```
curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17
```

**Comment by SirArthur7** [comment]
> > I found the following code snippet from Microsoft page to [Install the Microsoft ODBC driver for SQL Server (Linux)](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16&tabs=ubuntu18-install%2Calpine17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline), and it works perfectly fine-
> > ```
> > curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
> > curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
> > sudo apt-get update
> > sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17
> > ```
> 
> You should know that [adding a key to /etc/apt/trusted.gpg.d is insecure](https://stackoverflow.com/a/71384057):
> 
> > Adding a key to /etc/apt/trusted.gpg.d is insecure because it adds the key for all repositories. This is exactly why apt-key had to be deprecated.

Hey @mbomb007  thanks for letting me know, I wasn't aware of that. So what do you suggest I should do in order to get around this issue?

**Comment by mbearup** [comment]
@SirArthur7 the recommended path is to use the `signed-by` option as explained in the [Debian docs](https://wiki.debian.org/DebianRepository/UseThirdParty#Sources.list_entry).
This option specifies where the pubkey for a given repo can be found.
We (packages.microsoft.com) are updating our configs to align with this standard (see [the Debian 12 configs](https://packages.microsoft.com/config/debian/12/) as an example).
I can't speak to `apt-key` but I know that `add-apt-repository` still installs pubkeys to the "wrong" location (`/etc/apt/trusted.gpg.d`).
